### PR TITLE
Fix desktop file

### LINKED ISSUE #3: Found icon of unknown type 'unknown' in 'system/flatpak/flatpak/cc.nift.nsm/*', skipping it.
This Flatpak is triggering warnings in apt (and any other package manager that call appstreamcli) even without being installed:

```
$ flatpak list | grep 'cc\.nift\.nsm' # returns nothing
$

# appstreamcli refresh-cache --force

** (appstreamcli:18656): WARNING **: 11:20:37.242: Found icon of unknown type 'unknown' in 'system/flatpak/flatpak/cc.nift.nsm/*', skipping it.

** (appstreamcli:18656): WARNING **: 11:20:37.242: Found icon of unknown type 'unknown' in 'system/flatpak/flatpak/cc.nift.nsm/*', skipping it.
✔ Metadata cache was updated successfully.
```

### PR DESCRIPTION
**Pull request by hfiguiere**
- possibly fix #3 for good

### CODE REVIEW

**Comment by hfiguiere** [comment]
Updated patch for appdata.

**Comment by n-ham** [comment]
Thanks! Hope this fixes the warnings issue @laniakea64 was having..

**Comment by laniakea64** [comment]
Thanks for the quick response!  About how long is it expected to be before this update becomes live on Flathub?  I tried to check Flathub myself for the last updated date, but https://flathub.org/apps/details/cc.nift.nsm just says "App Not Found".

**Comment by hfiguiere** [comment]
The build is not done yet.... (only the test one).

**Comment by hfiguiere** [comment]
it is published.
but the page will be missing still since this is a CLI flatpak.

**Comment by laniakea64** [comment]
I had to run `flatpak update --appstream` to pick up this change, and now running `sudo appstreamcli refresh --force` no longer produces any warnings on my system.  Thank you both again :smiley:

**Pull request merged**
